### ISSUE TITLE
Not starting with status "connecting" when refreshing page and MetaMask has a pending request to connect 

### ISSUE THREAD

**Issue by guillermodlpa** [VGLoic/metamask-react#13]
First, I want to say how easy it was to plug and play `metamask-react`. Excellent library to hide the implementation details of interacting with MetaMask. Thank you! 🙌 

## Summary

When MetaMask has a pending request to connect and the user refreshes the page, `metamask-react` doesn't start with "connecting" status but with "notConnected", and calling `connect()` fails.

## Detailed steps

Testing different edge cases, I came up with one that I'm not sure that it's accounted for. For context, I'm making a demo project to learn with a test token called "KikiriCoin" ([repo](https://github.com/guillermodlpa/kikiricoin-website)). Given a page that offers the user a button "Connect" that, when clicked, executes the `connect` function of `useMetaMask`:

![Screen Shot showing web interface with connect button](https://user-images.githubusercontent.com/1557348/147877544-2d98cfd6-c195-47bc-9693-10ef9185e872.png)
_Screenshot showing web interface with connect button_

1. As a user, open the web page and click Connect. Don't perform any action on the MetaMask popup, leave the request unresolved.

![Screen Shot of meta mask connect request](https://user-images.githubusercontent.com/1557348/147877613-3ba4ccd8-ffeb-49ec-9e0b-e2a1575e31d4.png)
_Screenshot of meta mask connect request_

2. Refresh the web page. The MetaMask extension continues having the unresolved request.

Expected (ideally): the status given by `useMetaMask` is `connecting`.
Actual: the status given by `useMetaMask` is `notConnected`.

![Screen Shot of web interface after refreshing](https://user-images.githubusercontent.com/1557348/147877650-4c713a35-321f-4ead-b083-18d9be06c4c7.png)
_Screenshot of web interface after refreshing_

![Screen Shot of metamask extension icon](https://user-images.githubusercontent.com/1557348/147877658-becab21d-a195-41fc-8152-b0c54af1070d.png)
_Screenshot of metamask extension icon, with its pending request_

When the user clicks the "Connect" button again, an error is thrown "Request of type 'wallet_requestPermissions' already pending for origin http://localhost:3000. Please wait." with code `-32002`. At this point, the user is blocked from connecting unless they click the MetaMask extension icon in the browser to approve/cancel the request, or restart the browser.

![Screen Shot of console log error](https://user-images.githubusercontent.com/1557348/147877446-e9dccb53-ab64-42f3-bfa2-723e374e802e.png)
_Screenshot of console log error_

## Solutions

Fortunately, though, if the user opens the MetaMask extension, accepts the connection request, and refreshes the web page, the status returned by `useMetaMask` will be `connected` and things will work seamlessly.

I'm not sure if anything can be done from code to check if there's a pending request, in order to avoid this situation and inform the user appropriately. Ideally, we'd be able to call a function in `window.ethereum` to check if there was a pending request, and if that was the case, update the status to "connecting".

If not, it isn't the end of the world. I would just inform users to check their MetaMask extension for a pending connection request if I receive the error code `-32002`. Does that sound like the right approach?

**Comment by VGLoic** [comment]
Hey @guillermodlpa! Thanks a ton for this issue and all the details 🙏

I checked what the `window.ethereum` could offer but unfortunately it does not seem to have an exposed state for pending requests :(.

I think we can distinguish the two problems
1. `connect` throws while it should (probably) not, I would say idempotency would be expected,
2. `status` is not properly synced to `connecting`.

I don't have very strong solutions but here what I think we could do,

Solution 1 - minimal solution: calling `connect` will not throw if there is a pending connection request but make the state transition to `connecting` (technically speaking, we catch the error at the connect and if this is this exact one, we don't bubble up the error and go to `connecting` status). The sync problem will not be solved in this solution

Solution 2 - more agressive solution: we use the local storage to store connection requests and we check at synchronisation if there are any. We can additionally implement solution 1. Problem with this one is that we are introducing local storage usage which may lead to strange situations if the user is playing with it.

I would say the solution 1 is enough because as you said, it is some kind of edge case and I would expect future developments from MetaMask to get properly one day this state 🤔. What do you think about it? :)

**Comment by guillermodlpa** [comment]
Hi @VGLoic! Good analysis of the problem. Solution 1 makes sense to me. I'll fork the repo later today, experiment, and prepare a proposal!

**Comment by guillermodlpa** [comment]
I've been playing a bit with it today. I think a small solution along these lines achieves the result: `guillermodlpa/metamask-react` https://github.com/guillermodlpa/metamask-react/commit/46a614661290c725eeb7c0c5060f3932a7a7d30c

### The missing piece

Unfortunately, I confirmed that events don't get triggered when subscribing from the reloaded tab and the request had already started. So the sync won't work:

```js
// the listener set up after page refresh won't fire when approving the request :/
// Too bad, this would make all the flow work seamlessly!
ethereum.on('accountsChanged', () => {})
```

However, after approving, re-triggering the request `eth_requestAccounts` will work and `metamask-react` will change its `status` to `connected`. You can see that in action in the "after" demo below.

### Before

So I've had time to record a video of what the issue looks like, before the fix:

https://user-images.githubusercontent.com/1557348/147974248-6343bd26-2911-4d67-bf61-e45400f09292.mov

### After

Now a video showing the experience with the fix applied. These are the steps I took:

1. Open the test web page.
5. Trigger `connect`
3. Ignore the MetaMask popup, leaving the request pending.
4. Reload the web page.
5. Trigger `connect`. After the changes, it leaves the status to `connecting`. The button in the UI reflects that.
6. Open the MetaMask popup, log in and approve the request.
7. At this point, nothing happens. We couldn't add a listener to this request's completion :/ 
8. Trigger `connect` once more. It works because MetaMask is connected, accounts are retrieved, and the status transitions to `connected`.

https://user-images.githubusercontent.com/1557348/147974336-da80b51d-5476-40d8-a84e-44a8f4ca7fb3.mov

Context: I recorded that video on the kikiricoin-website project I mentioned, using `metamask-react` with the commit https://github.com/guillermodlpa/metamask-react/commit/46a614661290c725eeb7c0c5060f3932a7a7d30c  (paired with https://github.com/guillermodlpa/kikiricoin-website/commit/b83538a48c07b7cb0a7c0e6133f00c0646c17a43) and using test accounts in MetaMask, connected to Polygon Mumbai. Apologies for the low quality 😅 

### The problem with `connect`'s return value

With the solution I prepared (https://github.com/guillermodlpa/metamask-react/commit/46a614661290c725eeb7c0c5060f3932a7a7d30c), the method `requestAccounts`, and consequentially `connect`, don't return the array of accounts in this scenario. The only clean way I can think of managing this is making these methods return `void` in all cases, but that would change the library's interface.

What do you think? 🤔  Mmm, I think if we need to make `connect` return sometimes connected accounts and sometimes not, it might not be worth it. As you said, probably future developments of MetaMask would address this, and enable event listeners to be triggered for requests started on a prior page load.

**Comment by VGLoic** [comment]
Oh damn sorry, my bad, my idea was indeed not satisfying at all 😅.

Thanks a lot for taking the time to make all this work! :)

I would be a bit sad to have this double connect click.

There is a way to keep the signature and the functionality of the `connect` as it is now, it is not the prettiest but it might be ok. So in the `requestAccounts` function, we use the rpc request to request the accounts and consider it successful when it comes back. As you pointed out, in this particular situation of pending authorisation, it's not properly working because we return before the user really approved.

It happens that after the user connects, an event `accountsChanged` is immediately emitted with the connected account.

What we could do is, instead of saying `success is when the rpc request comes back`, we say `success is when we receive this first accountsChanged event`. Technically speaking, we would need, before firing the request, to listen to the first `accountsChanged` event then fire the request and finally resolve (the `resolve` would need to be passed in the callback of the listener) when the event has been received. What do you think about it? :) I usually don't like too much this pattern because assuming an event is coming at some time is a bit tricky but it might be a solution at our problem 🤔

**Comment by guillermodlpa** [comment]
Interesting, I'd like to try the approach. I'll let you know once I have tested it! Probably in a few days.

However, I'm not positive that it's gonna work. Subscribing with `ethereum.on('accountsChanged', ...)` didn't seem to work to listen to a pending request that started before page load (what I mentioned in my last comment in the section "The missing piece"). I'll make it just in case! 

I'll also look more into https://github.com/MetaMask/metamask-extension and their community forums to see if this behavior is intentional or can be improved 👍

**Comment by VGLoic** [comment]
I am not sure I was really clear in my previous message, what I though was something along these lines
```
function requestAccounts(
  dispatch: (action: Action) => void
): Promise<string[]> {
  const ethereum = (window as WindowInstanceWithEthereum).ethereum;

  dispatch({ type: "metaMaskConnecting" });

  return new Promise((resolve, reject) => {
    // Subscribe to next accounts changed event
    ethereum.once("accountsChanged", (accounts: string[]) => {
      dispatch({ type: "metaMaskConnected", payload: { accounts } });
      resolve(accounts);
    });

    // Trigger the request
    // If the user has not any pending request or has a pending request, it will not throw and we wait for the event accountsChanged to be triggered once the user has accepted on MetaMask 
    ethereum.request({
      method: "eth_requestAccounts",
    }).catch(err => {
      const requestAlreadyPending = false; // Need to be replaced
      if (requestAlreadyPending) return;
      dispatch({ type: "metaMaskPermissionRejected" });
      reject(err)
    });

  });
}
```
I can probably test that this week-end :)

**Comment by VGLoic** [comment]
Hey @guillermodlpa ! I understood only now what you meant with the missing piece 😱. Sorry my handling of this issue has been a disaster :(

I finally integrated a direct polling on `eth_accounts` additionally to the handling of the error you made, it will handle pending request when using the `connect`. I'm not a big fan of the solution but I hope this will only be temporary 😅 
The PR is https://github.com/VGLoic/metamask-react/pull/15

Please don't hesitate to tell me you think about it!

Oh and also, I'm happy to push the changes on your branch if you want to be part of the contributors here since you did most of the work :)

**Comment by guillermodlpa** [comment]
Hi @VGLoic. This is great, thanks for looking into it and proposing this solution! Like you explained in the comments, it's a complex solution to handle this edge case that hopefully would be addressed by MetaMask directly. I'll spend some time later today manually verifying those changes in my test application, and I'll confirm it's all good then.

Thanks for suggesting to push the changes in my branch! No worries, I'll find another way to contribute :) Love this project!
