### ISSUE TITLE
Brave crypto wallet detected as metamask wallet

### ISSUE THREAD

**Issue by JohnLowiePolyfill** [VGLoic/metamask-react#30]
### What version of React and MetaMask-React are you using?

- React: ^17.0.2
- MetaMask-React: ^2.4.0

### What is the current behavior?

there are 2 pages to my app, one is for connecting wallet, the other is to ask user to download the metamask extension if it is not detected.

while using the brave browser, i dont have the extension downloaded, but page will route to connect to wallet, instead of the extension page

### What is the expected behavior?

the user is suppose to get routed to the extension page if metamask is not detected. i think the brave crypto wallet is being detected as metamask

**Comment by VGLoic** [comment]
Hey @JohnLowiePolyfill! Thanks for this issue!

Do you have some CodeSandbox or code to help me understand what is happening please? :)

As I see the issue:
- either Brave crypto wallet is injecting the same type of object than MetaMask in the window: it can be check directly in the developer console by checking `window.ethereum && window.ethereum.isMetaMask` in this case, I would recommend you to report the issue directly to the Brave team,
- either `metamask-react` has an issue and the value `unavailable` of the `status` is wrongly computed, in this case, the issue is for this package and I need to fix it 😁 ,
- either there is an issue in your app for the redirection condition,
- either I miss something ahah

**Comment by JohnLowiePolyfill** [comment]
@VGLoic 

I found a different way to work around this issue! 

Basically I want my app to detect for a metamask wallet, but on the Brave browser it will detect the brave crypto wallet and set the `status` as `notConnected` instead of `unavailable`.  I have the user currently try to login and if it throws a server error it'll ask the user to download the extension.

**Comment by VGLoic** [comment]
Thanks for the information :)

Gonna take a look on my side about this Brave wallet stuff 👀
