### ISSUE TITLE
status is not changed from `initializing`

### ISSUE THREAD

**Issue by hiromaily** [VGLoic/metamask-react#31]
### What version of React and MetaMask-React are you using?

- React: 18.2.7
- MetaMask-React: 2.4.0

### What is the current behavior?

Though connect() is called, status is not changed from `initializing`
and Metamask popup is not displayed at all.

### What is the expected behavior?

First of all, Metamask popup must be displayed for password, connecting confirmation.

**Comment by VGLoic** [comment]
Hey @hiromaily! Thanks a lot for the issue!

Do you have any code snippet or a codesandbox available in order to replicate the issue please? :)

I tried to replicate using a codesandbox ([link](https://codesandbox.io/s/eager-swartz-x1sfo2?file=/src/App.tsx)) but without luck for now, can you tell me if the issue also appears on this codesandbox please?

**Comment by hiromaily** [comment]
Hi @VGLoic , given the codesandbox example is convincing.
I must be wrong somewhere.
Thanks for your great help :)

**Comment by VGLoic** [comment]
Hi @hiromaily! 

Thanks for the answer! I tried with Next.js, it also worked as expected on my side 🤔 

It could be an error related to the installed version of MetaMask or a clash with other extensions 🤔.

I'm closing the issue but don't hesitate to write here or re-open the issue if something looks wrong or if I can be of some help :)
