### ISSUE TITLE
How to avoid impersonation

### ISSUE THREAD

**Issue by ricoxor** [VGLoic/metamask-react#32]
### Open

Hello,
I use this repo for my project dashboard.
Is it possible to add a security to avoid people changing the 0x on the local storage to impersonate another 0x address?
For example, add a unique token returned from the server to make sure this 0x is the real one when someone calls the API.
I can't ask users to sign on every api call.
Thanks for you help.

**Comment by VGLoic** [comment]
Hello @ricoxor, thanks a lot for this issue!

So this package acts as a pure wrapper around the injected `ethereum` object by the MetaMask extension in the `window`, it only provides an API in order to interact easily with the MetaMask extension of the user but does not store anything in local storage or elsewhere :)

MetaMask extension itself allows a user to store a set of private keys in its browser (not in local storage though, it would be the internal state of the extension of the user) and to use them in order to sign messages or sign transactions. MetaMask also allows to send these transactions or read the state of a blockchain through a connection to a remote blockchain node. MetaMask has default connections for main networks but any user can provide their own node URL if he/she prefers.

The way impersonation can happen is in the case where an `ethereum` object is injected in the `window`, this object looks like the object injected by MetaMask but is actually not connected at all to the MetaMask extension. It would allow to use any address (like the one of someone else) in order to interact with the app. **However**, it would only allow to make reads on the blockchain state and it would never allow the impersonator to sign transaction like he/she was the real user because the impersonator would not have the private key of the user. Fun fact, there is actually an extension which does that, it is called `impersonator` if I recall properly.

State on the blockchain is fully public by design so impersonation for the reads is more a feature than a bug, the writes (signing transactions) are however protected by the ownership of a private key (and is not possible to impersonate).

Sorry for all this text, I prefer to give the full version, the TLDR is that this package can not protect against impersonation, it only makes sure to follow the guidelines of MetaMask in order to protect the user against a fake MetaMask. But even a fake MetaMask can not send transactions with the private key of a user stored in the "real" MetaMask.

However, if your project has an API, and you want to make the user interacting with your API is authenticated using his/her ethereum wallet, you should take a look at [sign in with Ethereum](https://login.xyz/)

Does that answer your question? :)

Don't hesitate to tell me if I completely misunderstood your point please :)

**Comment by ricoxor** [comment]
Hello @VGLoic ,
Thank you very much for your complete answer, I understand better it's very clear. I really appreciate that you took the time to explain all this!
I'm going to check out the siwe package from https://login.xyz/!

**Comment by VGLoic** [comment]
That's great to hear, my pleasure :)

I'm closing this issue but don't hesitate to re-open it or continue the conversation here!
