### ISSUE TITLE
I have two question about useConnectedMetamask

### ISSUE THREAD

**Issue by juanluismm521** [VGLoic/metamask-react#35]
Hello, I like this npm package. It's very simple and nice to use for connect react with metamask. 
However, I have a question. When I use useConnectedMetamask works fine except if you reload the page (with f5 for example) that show me a exception in the console. 

Another question I have is if I could disconnect from metamask using a botton in my web app. 

Thanks you!

**Comment by VGLoic** [comment]
Hello @juanluismm521 ! Sorry for the late answer and thanks a lot for this issue :)

> When I use useConnectedMetamask works fine except if you reload the page (with f5 for example) that show me a exception in the console.

Yes unfortunately this is by design, the app needs to perform the synchronisation between the Metamask extension of the user and the app on which the user is. This process is asynchronous, as a consequence this library cannot synchronously assume a user is `connected`. That is why the `status` exposed by the library will always start as `initializing` and then resolve into `connected` if the user is connected (or `notConnected` is the user is not connected).

As a solution, I would advise you to always check that MetaMask is properly connected before rendering components which use `useConnectedMetaMask`, as a simple example it would be something like
```
function App() {
  const { status } = useMetaMask();

  // We wait for the sync process to finish
  if (status === 'initializing') return null;

  // User is not connected, we can handle the connection flow
  if (status !== 'connected') return <NotConnectedApp />;

  // We are sure the user is connected, we can use `useConnectedMetaMask` safely in `ConnectedApp` or any of its children
  return <ConnectedApp />
}
```

> Another question I have is if I could disconnect from metamask using a botton in my web app

That is a very good question and a lot of people are asking about this. Unfortunately, as far as I know MetaMask does not expose (yet!) a way to programatically disconnect a user from an app :(. For now, the only real disconnection  must be done by the user in its MetaMask extension. If MetaMask exposes this disconnect API at some point, I would be more than happy to take it into account here :)


Does that answer your questions?

**Comment by juanluismm521** [comment]
Oh thanks you for your answer! Yes that way it's a very simple and useful for me.

I will wait for metamask disconnect API but it isn't very important. 

Thanks and have a good day :)
