### ISSUE TITLE
How to identify the balance on the metamask account already connected?

### ISSUE THREAD

**Issue by heras1991** [VGLoic/metamask-react#8]
Hi VGLoic, thank you very much for this amazing library.

I have inspected the code without success to identify the balance of ERC20 and ERC721 tokens belonging to a connected account. 

The only method I found is: eth_getBalance but only returns main balance of the chain.

Could you please lead me in the way to get another ERC721/ERC20 token balance? (not need to interact with it, just to know the balance)

Thank you again!

**Comment by VGLoic** [comment]
Hey @heras1991! Thanks a lot for the kind word!

So indeed this package only manages what is called the `web3 provider` layer, the exposed `ethereum` object is the one MetaMask injects directly in the `window` and does not come (intentionally) with a lot of features

In order to manage interactions with the chain, balance/block fetching or contract interactions, people generally use other libraries, the two major ones are [ethersjs](https://docs.ethers.io/v5/) or [web3js](https://web3js.readthedocs.io/en/v1.5.2/).

These libraries take as an entry param a `web3 provider`, so in the case of this package, the `ethereum` object :).

I would recommend you to take a look at [this part](https://web3js.readthedocs.io/en/v1.5.2/) of the ethersjs documentation which specifically describes the ERC20 case :). The ERC721 will be mostly similar at the exception of the ABI.

Feel free to tell me if I am not clear or you still have other questions :)

**Comment by heras1991** [comment]
Thank you very much for the explication. I found the way to do it with web3.js 👍 

I strongly suggest you implement the integration with web3.js to store  the balance of an ERC20 token in the same context. This is a very popular use-case for blockchain devlopers and your library is almost there.

**Comment by VGLoic** [comment]
Thanks a lot for the idea! I will consider doing a separate package for these kind of use cases :)

I would love to keep this package far away from the battle of various use cases and/or choice of libraries such as web3.js/ethers.js

Are you okay if I close this issue? :)

**Comment by heras1991** [comment]
sure! Please, close it. Thank you

**Comment by VGLoic** [comment]
Thanks!
